apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-web-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-web-sidecar
  template:
    metadata:
      labels:
        app: management-web-sidecar
    spec:
      enableServiceLinks: false
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: management-web-sidecar
          image: ghcr.io/podverse/metaboost/management-web-sidecar
          imagePullPolicy: Always
          ports:
            - containerPort: 4101
          envFrom:
            - configMapRef:
                name: metaboost-management-web-runtime-config
