apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: metaboost-management-web-config
    envs:
      - source/management-web.env
  - name: metaboost-management-web-runtime-config
    envs:
      - source/management-web-sidecar.env

replacements:
  - source:
      kind: Service
      name: management-web
      fieldPath: spec.ports.0.port
    targets:
      - select:
          kind: Service
          name: management-web
        fieldPaths:
          - spec.ports.0.targetPort
      - select:
          kind: Deployment
          name: management-web
        fieldPaths:
          - spec.template.spec.containers.0.ports.0.containerPort
          - spec.template.spec.containers.0.readinessProbe.tcpSocket.port
          - spec.template.spec.containers.0.livenessProbe.tcpSocket.port
