apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metaboost-local

resources:
  - namespace.yaml
  - pvc.yaml
  - workloads.yaml
  - services.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: metaboost-app-db-init-scripts
    files:
      - ../db/source/bootstrap/0001_create_app_db_users.sh
  - name: metaboost-management-init-scripts
    files:
      - ../db/source/bootstrap/0002_setup_management_database.sh
      - ../db/source/bootstrap/0006_management_grants.sh
  - name: metaboost-db-init-scripts
    files:
      - ../db/source/bootstrap/0003_linear_baseline.sql.gz
      - ../db/source/bootstrap/0004_seed_linear_migration_history.sql
