apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metaboost-postgres-data
  namespace: metaboost-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metaboost-valkey-data
  namespace: metaboost-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
