apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boilerplate-postgres-data
  namespace: boilerplate-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boilerplate-valkey-data
  namespace: boilerplate-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
