apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metaboost-alpha-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: metaboost
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: metaboost-db
      jqPathExpressions:
        - .spec.volumeClaimTemplates[0].apiVersion
        - .spec.volumeClaimTemplates[0].kind
  source:
    repoURL: https://github.com/podverse/metaboost.git
    targetRevision: X.X.X-staging.N
    path: infra/k8s/alpha/db
  destination:
    server: https://kubernetes.default.svc
    namespace: metaboost-alpha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
