apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metaboost-alpha-management-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: metaboost
  source:
    repoURL: https://github.com/podverse/metaboost.git
    targetRevision: X.X.X-staging.N
    path: infra/k8s/alpha/management-api
  destination:
    server: https://kubernetes.default.svc
    namespace: metaboost-alpha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
