apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metaboost-alpha-management-web
  namespace: argocd
spec:
  project: metaboost
  source:
    repoURL: https://github.com/podverse/metaboost.git
    targetRevision: 0.1.10-staging.0
    path: infra/k8s/alpha/management-web
  destination:
    server: https://kubernetes.default.svc
    namespace: metaboost-alpha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
