apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metaboost-alpha-ops
  namespace: argocd
spec:
  project: metaboost
  source:
    repoURL: https://github.com/podverse/metaboost.git
    targetRevision: develop
    path: infra/k8s/alpha/ops
  destination:
    server: https://kubernetes.default.svc
    namespace: metaboost-alpha
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
