apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: boilerplate-local
spec:
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: boilerplate-local
spec:
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: management-api
  namespace: boilerplate-local
spec:
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: management-web
  namespace: boilerplate-local
spec:
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: boilerplate-local
spec:
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: boilerplate-local
spec:
  type: LoadBalancer
