#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates docs/development/ENV-VARS-CATALOG.md — exhaustive classification env vars,
# merge defaults for local_docker vs remote_k8s, and K8s placement per kind/group.
# Same merge path as metaboost-env.rb merge-env (no --extra-env).

require_relative 'lib/metaboost_env_merge'

# Must match scripts/k8s-env/k8s-env-render-manifest.inc.sh K8S_ENV_RENDER_WORKLOADS
K8S_ENV_RENDER_WORKLOADS = %w[
  db
  valkey
  api
  web-sidecar
  management-api
  management-web-sidecar
].freeze

# Must match scripts/k8s-env/render_k8s_env.rb DEPLOYMENT_PATCH_TARGETS (for notes)
DEPLOYMENT_PATCH_TARGETS = {
  'api' => %w[api api],
  'db' => %w[postgres postgres],
  'management-api' => %w[management-api management-api],
  'management-web-sidecar' => %w[management-web-sidecar management-web-sidecar],
  'valkey' => %w[valkey valkey],
  'web-sidecar' => %w[web-sidecar web-sidecar]
}.freeze

# Must match k8s-env-render-manifest.inc.sh overlay_dir_for_workload
def overlay_dir_for_workload(group)
  case group
  when 'api' then 'api'
  when 'management-api' then 'management-api'
  when 'web-sidecar' then 'web'
  when 'management-web-sidecar' then 'management-web'
  when 'db' then 'db'
  when 'valkey' then 'keyvaldb'
  else ''
  end
end

def usage(msg = nil)
  warn("Error: #{msg}") if msg
  warn <<~USAGE
    Usage: env-vars-catalog.rb [--output PATH]
      Writes exhaustive ENV-VARS-CATALOG.md to PATH, or stdout when --output is omitted.
  USAGE
  exit 1
end

args = ARGV.dup
output_path = nil
until args.empty?
  case args.shift
  when '--output'
    output_path = args.shift
  when '-h', '--help'
    usage
  else
    usage('unknown arg')
  end
end

def md_escape_cell(s)
  return '—' if s.nil?

  str = s.to_s
  return '*(empty)*' if str.empty?

  str.gsub('|', '\\|').gsub("\n", ' ')
end

def merged_env_for_profile(group_name, profile)
  classification = MetaboostEnvMerge.merged_classification(profile)
  flat = MetaboostEnvMerge.flatten_env_group_env(classification, group_name)
  merged = MetaboostEnvMerge.apply_env_file_overlays(flat, [])
  merged = MetaboostEnvMerge.apply_locale_next_public_sync(merged, group_name)
  merged = MetaboostEnvMerge.apply_auth_mode_next_public_sync(merged, group_name)
  merged = MetaboostEnvMerge.apply_info_next_public_sync(merged, group_name)
  MetaboostEnvMerge.reorder_env_map_to_group_vars(merged, classification, group_name)
end

def k8s_placement(group_name, kind, classification)
  wl = classification.dig(MetaboostEnvMerge::CLASSIFICATION_ENV_GROUPS_KEY, group_name)
  no_render = wl.is_a?(Hash) && wl['no_env_from']

  suffix = group_name.to_s
  odir = overlay_dir_for_workload(group_name)
  cm_rel = odir.empty? ? nil : "#{odir}/source/metaboost-#{suffix}-config.env"
  cm_named = "metaboost-#{suffix}-config"
  sec_named = "metaboost-#{suffix}-secrets"

  if no_render
    return 'No render for this workload (`no_env_from`); vars still merged for host/runtime consumers.'
  end

  unless K8S_ENV_RENDER_WORKLOADS.include?(group_name.to_s)
    return 'Classification-only merge group (bucket/split/inherited elsewhere); no GitOps overlay ConfigMap for this group.'
  end

  k = kind.to_s
  if k == 'source_only'
    return "Merged locally; **not** in pod env from CM/Secret (`kind: source_only`). Dotenv path would be #{cm_rel || 'n/a'} for reference only."
  end

  parts = []
  parts << "`#{cm_rel}` → ConfigMap `#{cm_named}`" if %w[literal config].include?(k)
  if k == 'secret'
    parts << "Secret `#{sec_named}` (`stringData`)"
    targets = DEPLOYMENT_PATCH_TARGETS[group_name.to_s]
    if targets
      dep, ctr = targets
      parts << "`deployment-secret-env.yaml` → `secretKeyRef` → Deployment `#{dep}` / container `#{ctr}`"
    end
  end
  parts.join('; ')
end

def env_group_names(classification)
  groups = classification[MetaboostEnvMerge::CLASSIFICATION_ENV_GROUPS_KEY]
  return [] unless groups.is_a?(Hash)

  groups.keys.sort
end

remote_class = MetaboostEnvMerge.merged_classification('remote_k8s')

lines = []
lines << '# ENV-VARS-CATALOG'
lines << ''
lines << '<!-- Generated by `scripts/env-classification/env-vars-catalog.rb`. Do not edit by hand. -->'
lines << ''
lines << 'Exhaustive list of variables from [`infra/env/classification/base.yaml`](../infra/env/classification/base.yaml) and profile overlays under [`infra/env/overrides/`](../infra/env/overrides/), merged the same way as `scripts/env-classification/metaboost-env.rb merge-env` (no `--extra-env` files).'
lines << ''
lines << '- **Default (local_docker)** / **Default (remote_k8s)** — effective values after profile overlay merge and the same sync steps as merge-env (`NEXT_PUBLIC_*` mirrors for sidecars, etc.). Empty string is shown as *(empty)*.'
lines << '- **K8s (remote_k8s)** — where keys go when `scripts/k8s-env/render-k8s-env.sh` runs with profile `remote_k8s` (see [K8S-ENV-RENDER.md](K8S-ENV-RENDER.md)). This column describes classification `kind`, not live cluster values. `local_generator` / plain Secret reuse during render are out of scope here.'
lines << ''
lines << '---'
lines << ''
lines << '## Default comparison (`local_docker` vs `remote_k8s`)'
lines << ''

env_group_names(remote_class).each do |group_name|
  wl = remote_class.dig(MetaboostEnvMerge::CLASSIFICATION_ENV_GROUPS_KEY, group_name)
  next unless wl.is_a?(Hash)

  specs = MetaboostEnvMerge.effective_env_group_var_specs(remote_class, group_name)
  next if specs.empty?

  l_env = merged_env_for_profile(group_name, 'local_docker')
  r_env = merged_env_for_profile(group_name, 'remote_k8s')

  lines << "### `#{group_name}`"
  lines << ''
  lines << '| Variable | Kind | Default (local_docker) | Default (remote_k8s) | K8s (remote_k8s) |'
  lines << '| --- | --- | --- | --- | --- |'

  MetaboostEnvMerge.effective_var_emit_order(remote_class, group_name).each do |key|
    spec = specs[key]
    next unless spec.is_a?(Hash)

    kind = spec['kind'].to_s
    k8s_cell = k8s_placement(group_name, kind, remote_class)
    lines << "| `#{key}` | `#{kind}` | #{md_escape_cell(l_env[key])} | #{md_escape_cell(r_env[key])} | #{k8s_cell} |"
  end
  lines << ''
end

out = lines.join("\n") + "\n"

if output_path
  File.write(output_path, out, encoding: 'UTF-8')
else
  print out
end
