apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: metaboost
  namespace: argocd
spec:
  description: Metaboost project applications
  sourceRepos:
    - https://github.com/podverse/metaboost.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: metaboost-alpha
      server: https://kubernetes.default.svc
    - namespace: metaboost-beta
      server: https://kubernetes.default.svc
    - namespace: metaboost-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
