#!/bin/bash
# Runs after 0004_load_management_schema.sh loads 0005_management_schema.sql.frag so tables exist. Aligned with makefiles/local/Makefile.local.test.mk (test_db_init_management).
set -e

: "${DB_MANAGEMENT_READ_USER:?Missing DB_MANAGEMENT_READ_USER}"
: "${DB_MANAGEMENT_READ_WRITE_USER:?Missing DB_MANAGEMENT_READ_WRITE_USER}"
: "${DB_MANAGEMENT_NAME:?Missing DB_MANAGEMENT_NAME}"

MANAGEMENT_DB_NAME="${DB_MANAGEMENT_NAME}"
PG_SUPERUSER="${DB_USER:-${POSTGRES_USER:-user}}"

psql -v ON_ERROR_STOP=1 --username "$PG_SUPERUSER" -d "${MANAGEMENT_DB_NAME}" <<SQL
GRANT CONNECT ON DATABASE ${MANAGEMENT_DB_NAME} TO ${DB_MANAGEMENT_READ_USER}, ${DB_MANAGEMENT_READ_WRITE_USER};
GRANT USAGE ON SCHEMA public TO ${DB_MANAGEMENT_READ_USER}, ${DB_MANAGEMENT_READ_WRITE_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_MANAGEMENT_READ_USER};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${DB_MANAGEMENT_READ_USER};
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO ${DB_MANAGEMENT_READ_WRITE_USER};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${DB_MANAGEMENT_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${DB_MANAGEMENT_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${DB_MANAGEMENT_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO ${DB_MANAGEMENT_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO ${DB_MANAGEMENT_READ_WRITE_USER};
SQL
