#!/bin/bash
# Creates app DB migrator/read-write/read users and grants for least-privilege runtime access.
set -e

: "${DB_APP_OWNER_USER:?Missing DB_APP_OWNER_USER}"
: "${DB_APP_OWNER_PASSWORD:?Missing DB_APP_OWNER_PASSWORD}"
: "${DB_APP_MIGRATOR_USER:?Missing DB_APP_MIGRATOR_USER}"
: "${DB_APP_MIGRATOR_PASSWORD:?Missing DB_APP_MIGRATOR_PASSWORD}"
: "${DB_APP_READ_WRITE_USER:?Missing DB_APP_READ_WRITE_USER}"
: "${DB_APP_READ_WRITE_PASSWORD:?Missing DB_APP_READ_WRITE_PASSWORD}"
: "${DB_APP_READ_USER:?Missing DB_APP_READ_USER}"
: "${DB_APP_READ_PASSWORD:?Missing DB_APP_READ_PASSWORD}"
: "${DB_APP_NAME:?Missing DB_APP_NAME}"

psql -v ON_ERROR_STOP=1 --username "$DB_APP_OWNER_USER" -d "$DB_APP_NAME" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_APP_MIGRATOR_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_APP_MIGRATOR_USER}', '${DB_APP_MIGRATOR_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_APP_READ_WRITE_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_APP_READ_WRITE_USER}', '${DB_APP_READ_WRITE_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_APP_READ_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_APP_READ_USER}', '${DB_APP_READ_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${DB_APP_MIGRATOR_USER}', '${DB_APP_MIGRATOR_PASSWORD}');
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${DB_APP_READ_WRITE_USER}', '${DB_APP_READ_WRITE_PASSWORD}');
    EXECUTE format('ALTER USER %I WITH PASSWORD %L', '${DB_APP_READ_USER}', '${DB_APP_READ_PASSWORD}');
END
\$\$;

GRANT CONNECT ON DATABASE ${DB_APP_NAME} TO ${DB_APP_MIGRATOR_USER}, ${DB_APP_READ_WRITE_USER}, ${DB_APP_READ_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${DB_APP_MIGRATOR_USER};
SQL

psql -v ON_ERROR_STOP=1 --username "$DB_APP_MIGRATOR_USER" -d "$DB_APP_NAME" <<SQL
GRANT USAGE ON SCHEMA public TO ${DB_APP_READ_WRITE_USER}, ${DB_APP_READ_USER};

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO ${DB_APP_READ_WRITE_USER};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${DB_APP_READ_WRITE_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_APP_READ_USER};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${DB_APP_READ_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO ${DB_APP_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO ${DB_APP_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${DB_APP_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${DB_APP_READ_USER};
SQL
