#!/bin/bash
# Creates management database owner/migrator/read-write/read roles and grants.
set -e

: "${DB_APP_OWNER_USER:?Missing DB_APP_OWNER_USER}"
: "${DB_APP_OWNER_PASSWORD:?Missing DB_APP_OWNER_PASSWORD}"
: "${DB_APP_NAME:?Missing DB_APP_NAME}"
: "${DB_MANAGEMENT_OWNER_USER:?Missing DB_MANAGEMENT_OWNER_USER}"
: "${DB_MANAGEMENT_OWNER_PASSWORD:?Missing DB_MANAGEMENT_OWNER_PASSWORD}"
: "${DB_MANAGEMENT_MIGRATOR_USER:?Missing DB_MANAGEMENT_MIGRATOR_USER}"
: "${DB_MANAGEMENT_MIGRATOR_PASSWORD:?Missing DB_MANAGEMENT_MIGRATOR_PASSWORD}"
: "${DB_MANAGEMENT_READ_WRITE_USER:?Missing DB_MANAGEMENT_READ_WRITE_USER}"
: "${DB_MANAGEMENT_READ_WRITE_PASSWORD:?Missing DB_MANAGEMENT_READ_WRITE_PASSWORD}"
: "${DB_MANAGEMENT_READ_USER:?Missing DB_MANAGEMENT_READ_USER}"
: "${DB_MANAGEMENT_READ_PASSWORD:?Missing DB_MANAGEMENT_READ_PASSWORD}"

MANAGEMENT_DB_NAME="${DB_MANAGEMENT_NAME:-metaboost_management}"

psql -v ON_ERROR_STOP=1 --username "$DB_APP_OWNER_USER" --dbname "$DB_APP_NAME" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_MANAGEMENT_OWNER_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_OWNER_USER}', '${DB_MANAGEMENT_OWNER_PASSWORD}');
    ELSE
        EXECUTE format('ALTER USER %I WITH NOCREATEDB NOCREATEROLE PASSWORD %L', '${DB_MANAGEMENT_OWNER_USER}', '${DB_MANAGEMENT_OWNER_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_MANAGEMENT_MIGRATOR_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_MIGRATOR_USER}', '${DB_MANAGEMENT_MIGRATOR_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_MANAGEMENT_READ_WRITE_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_READ_WRITE_USER}', '${DB_MANAGEMENT_READ_WRITE_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_MANAGEMENT_READ_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_READ_USER}', '${DB_MANAGEMENT_READ_PASSWORD}');
    END IF;
END
\$\$;
SQL

DB_EXISTS=$(psql -U "$DB_APP_OWNER_USER" -d "$DB_APP_NAME" -tAc "SELECT 1 FROM pg_database WHERE datname='${MANAGEMENT_DB_NAME}'")
if [ "$DB_EXISTS" != "1" ]; then
  psql -U "$DB_APP_OWNER_USER" -d "$DB_APP_NAME" -c "CREATE DATABASE ${MANAGEMENT_DB_NAME} OWNER ${DB_MANAGEMENT_OWNER_USER};"
fi

psql -v ON_ERROR_STOP=1 --username "$DB_APP_OWNER_USER" --dbname "$DB_APP_NAME" -c "ALTER USER \"${DB_MANAGEMENT_OWNER_USER}\" WITH PASSWORD '${DB_MANAGEMENT_OWNER_PASSWORD}';"
psql -v ON_ERROR_STOP=1 --username "$DB_APP_OWNER_USER" --dbname "$DB_APP_NAME" -c "ALTER USER \"${DB_MANAGEMENT_MIGRATOR_USER}\" WITH PASSWORD '${DB_MANAGEMENT_MIGRATOR_PASSWORD}';"
psql -v ON_ERROR_STOP=1 --username "$DB_APP_OWNER_USER" --dbname "$DB_APP_NAME" -c "ALTER USER \"${DB_MANAGEMENT_READ_WRITE_USER}\" WITH PASSWORD '${DB_MANAGEMENT_READ_WRITE_PASSWORD}';"
psql -v ON_ERROR_STOP=1 --username "$DB_APP_OWNER_USER" --dbname "$DB_APP_NAME" -c "ALTER USER \"${DB_MANAGEMENT_READ_USER}\" WITH PASSWORD '${DB_MANAGEMENT_READ_PASSWORD}';"
psql -v ON_ERROR_STOP=1 --username "$DB_APP_OWNER_USER" --dbname "$DB_APP_NAME" -c "ALTER DATABASE \"${MANAGEMENT_DB_NAME}\" OWNER TO \"${DB_MANAGEMENT_OWNER_USER}\";"

psql -v ON_ERROR_STOP=1 --username "$DB_MANAGEMENT_OWNER_USER" --dbname "$MANAGEMENT_DB_NAME" <<SQL
GRANT CONNECT ON DATABASE ${MANAGEMENT_DB_NAME} TO ${DB_MANAGEMENT_MIGRATOR_USER}, ${DB_MANAGEMENT_READ_WRITE_USER}, ${DB_MANAGEMENT_READ_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${DB_MANAGEMENT_MIGRATOR_USER};
SQL

psql -v ON_ERROR_STOP=1 --username "$DB_MANAGEMENT_MIGRATOR_USER" --dbname "$MANAGEMENT_DB_NAME" <<SQL
DO \$\$
BEGIN
    IF NOT has_schema_privilege('${DB_MANAGEMENT_READ_WRITE_USER}', 'public', 'USAGE') THEN
        EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', '${DB_MANAGEMENT_READ_WRITE_USER}');
    END IF;

    IF NOT has_schema_privilege('${DB_MANAGEMENT_READ_USER}', 'public', 'USAGE') THEN
        EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', '${DB_MANAGEMENT_READ_USER}');
    END IF;
END
\$\$;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${DB_MANAGEMENT_READ_WRITE_USER};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${DB_MANAGEMENT_READ_WRITE_USER};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_MANAGEMENT_READ_USER};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${DB_MANAGEMENT_READ_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_MANAGEMENT_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO ${DB_MANAGEMENT_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${DB_MANAGEMENT_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${DB_MANAGEMENT_READ_USER};
SQL
