#!/bin/bash
# Creates app DB read-only and read-write users (names from DB_APP_READ_USER, DB_APP_READ_WRITE_USER).
# Runs first in docker-entrypoint-initdb.d/ so ALTER DEFAULT PRIVILEGES apply to tables created by 0003_app_schema.sql (k8s path).
set -e

: "${DB_APP_READ_USER:?Missing DB_APP_READ_USER}"
: "${DB_APP_READ_WRITE_USER:?Missing DB_APP_READ_WRITE_USER}"
: "${DB_APP_READ_PASSWORD:?Missing DB_APP_READ_PASSWORD}"
: "${DB_APP_READ_WRITE_PASSWORD:?Missing DB_APP_READ_WRITE_PASSWORD}"
: "${DB_APP_NAME:?Missing DB_APP_NAME}"

PG_SUPERUSER="${DB_USER:-${POSTGRES_USER:-user}}"

# psql defaults the database name to the username; POSTGRES_USER=user does not create a DB named "user".
# Connect to the app DB (POSTGRES_DB / DB_APP_NAME) so schema grants and ALTER DEFAULT PRIVILEGES target it.
psql -v ON_ERROR_STOP=1 --username "$PG_SUPERUSER" -d "$DB_APP_NAME" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_APP_READ_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_APP_READ_USER}', '${DB_APP_READ_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_APP_READ_WRITE_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_APP_READ_WRITE_USER}', '${DB_APP_READ_WRITE_PASSWORD}');
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${DB_APP_NAME} TO ${DB_APP_READ_USER}, ${DB_APP_READ_WRITE_USER};
GRANT USAGE ON SCHEMA public TO ${DB_APP_READ_USER}, ${DB_APP_READ_WRITE_USER};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_APP_READ_USER};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${DB_APP_READ_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${DB_APP_READ_WRITE_USER};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${DB_APP_READ_WRITE_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${DB_APP_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${DB_APP_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_APP_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO ${DB_APP_READ_WRITE_USER};
SQL
