apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-sidecar
  template:
    metadata:
      labels:
        app: web-sidecar
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: web-sidecar
          image: ghcr.io/podverse/boilerplate/web-sidecar
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
          envFrom:
            - configMapRef:
                name: boilerplate-web-sidecar-config
          env:
            - name: API_SERVER_BASE_URL
              value: http://api:4000
