apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service-web.yaml
  - service-web-sidecar.yaml
  - deployment-web.yaml
  - deployment-web-sidecar.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: metaboost-web-config
    envs:
      - source/web.env
  - name: metaboost-web-runtime-config
    envs:
      - source/web-sidecar.env
