apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metaboost-alpha-web
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: <argocd-project>
  source:
    repoURL: <gitops-repo-url>
    targetRevision: <gitops-branch>
    path: apps/metaboost-alpha/web
  destination:
    server: https://kubernetes.default.svc
    namespace: metaboost-alpha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
